# Generated by Django 3.2.9 on 2021-11-26 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0002_google'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employe',
        ),
        migrations.AlterModelTable(
            name='employe',
            table='employe',
        ),
    ]
