# Generated by Django 3.2.9 on 2021-11-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subject',
        ),
    ]
