# Generated by Django 3.2.9 on 2021-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0007_remove_employee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.FileField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
