# Generated by Django 3.2.9 on 2021-11-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0008_employee_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
